title: Tasmota Device Templates Repository
description: Database of templates for devices supported in Tasmota
url: "https://blakadder.github.io"
baseurl: "/templates"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
remote_theme: alexander-heimbuch/millidocs

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  sass_dir: _sass
  style: compressed

collections:
  templates:
    output: true
    permalink: /:title.html

defaults:
  - scope:
      path: ""
      type: "templates"
    values:
      layout: "templates"

plugins:
  - jekyll-seo-tag
google_analytics: UA-140681905-1