collections:
  templates:
    output: true
    permalink: /:title.html

defaults:
  - scope:
      path: ""
      type: "templates"
    values:
      layout: "templates"
future: true
markdown_ext: "markdown, mkdown, mkdn, mkd, md"
highlighter: rouge
title: Tamota Device Templates
url: "https://blakadder.github.io"
baseurl: "/templates"
