collections:
  templates:
    output: true
    permalink: /:title.html

defaults:
  - scope:
      path: ""
      type: "templates"
    values:
      layout: "templates"
future: true
baseurl: "templates"
