collections:
  templates:
    output: true
    permalink: /:collection/:collection/:title.html

defaults:
  - scope:
      path: ""
      type: "templates"
    values:
      layout: "templates"
future: true
