# page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - index_files: 'true'
    data: 'templates'
    name: 'name'
    template: 'user-devices'
    dir: 'templates'
collections:
  templates:
    output: true
