collections:
  templates:
    output: true
    permalink: /:title.html

defaults:
  - scope:
      path: ""
      type: "templates"
    values:
      layout: "templates"
future: true
highlighter: rouge
title: Tasmota Device Templates
url: "https://blakadder.github.io"
baseurl: "/templates"
